parameters:
    nova_ezcloudinary.default.authentification:
        cloud_name: demo
        api_key: "P L O P I X"
        api_secret: "42"
    nova_ezcloudinary.default.cloudinary_disabled: false
    nova_ezcloudinary.default.cloudinary_fecth_proxy:
            host: ~
            port: ~
    nova_ezcloudinary.default.cloudinary_variations:
            optimized_medium:
                ezreference_variation: medium
                filters:
                    fetch_format: 'auto'
