parameters:

services:
    _defaults:
        autowire: true
        public: false
        bind:
            $logger: "@monolog.logger.novaezmailing"

    Novactive\Bundle\eZMailingBundle\Command\:
        resource: '../../Command'
        tags: ["console.command"]

    Novactive\Bundle\eZMailingBundle\Form\:
        resource: '../../Form'
        tags: ["form.type"]

    Novactive\Bundle\eZMailingBundle\Security\Voter\:
        resource: '../../Security/Voter'
        tags: ["security.voter"]

    Novactive\Bundle\eZMailingBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Novactive\Bundle\eZMailingBundle\Core\Provider\:
        resource: '../../Core/Provider'

    Novactive\Bundle\eZMailingBundle\Core\Processor\:
        resource: '../../Core/Processor'

    Novactive\Bundle\eZMailingBundle\Core\Modifier\:
        resource: '../../Core/Modifier'
        tags: [novaezmailing.content.modifier]

    Novactive\Bundle\eZMailingBundle\Core\Provider\MailingContent:
        arguments: [!tagged novaezmailing.content.modifier]

    Novactive\Bundle\eZMailingBundle\Menu\Builder:
        arguments: ["@knp_menu.factory"]

    novaezmailing.menu.main:
        class: Knp\Menu\MenuItem
        factory: 'Novactive\Bundle\eZMailingBundle\Menu\Builder:createAdminMenu'
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: novaezmailing.menu.admin }

    novaezmailing.menu.campaigns:
        class: Knp\Menu\MenuItem
        factory: 'Novactive\Bundle\eZMailingBundle\Menu\Builder:createCampaignMenu'
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
        tags:
            - { name: knp_menu.menu, alias: novaezmailing.menu.campaigns }

    novaezmailing.menu.save_cancel:
        class: Knp\Menu\MenuItem
        factory: 'Novactive\Bundle\eZMailingBundle\Menu\Builder:createSaveCancelMenu'
        tags:
            - { name: knp_menu.menu, alias: novaezmailing.menu.save_cancel }

    Novactive\Bundle\eZMailingBundle\Core\AjaxGuard: ~

    Novactive\Bundle\eZMailingBundle\Listener\EntityContentLink:
       tags:
            - { name: doctrine.orm.entity_listener }

    Novactive\Bundle\eZMailingBundle\Listener\MailingWorkflow:
        tags:
            - { name: kernel.event_listener, event: workflow.mailing.leave }

    Novactive\Bundle\eZMailingBundle\Listener\PreContentView:
        tags:
            - { name: kernel.event_listener, event: ezpublish.pre_content_view, method: onPreContentView }

    # Mailers
    Novactive\Bundle\eZMailingBundle\Core\Mailer\Factory: ~

    Novactive\Bundle\eZMailingBundle\Core\Mailer\Simple:
        public: true
        factory: 'Novactive\Bundle\eZMailingBundle\Core\Mailer\Factory:get'
        arguments: ['simple_mailer']

    Novactive\Bundle\eZMailingBundle\Core\Mailer\Mailing:
        factory: 'Novactive\Bundle\eZMailingBundle\Core\Mailer\Factory:get'
        arguments: ['mailing_mailer']

    # Twig
    Novactive\Bundle\eZMailingBundle\Twig\Extension:
        tags: ['twig.extension']

    # Doctrine
    Novactive\Bundle\eZMailingBundle\DataFixtures\:
        resource: '../../DataFixtures'
        tags: ['doctrine.fixture.orm']

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    ez_mailing.io_service:
        class: Novactive\Bundle\eZMailingBundle\Core\IOService
        arguments: ['@ez_mailing.ezpublish.core.io_service']