parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\eZProtectedContentBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Novactive\Bundle\eZProtectedContentBundle\Core\Tab\ProtectContent:
        tags:
            - { name: ezplatform.tab, group: location-view }

    Novactive\Bundle\eZProtectedContentBundle\Listener\EntityContentLink:
        tags:
            - { name: doctrine.orm.entity_listener }

    Novactive\Bundle\eZProtectedContentBundle\Listener\PreContentView:
        tags:
            - { name: kernel.event_listener, event: ezpublish.pre_content_view, method: onPreContentView }

    Novactive\Bundle\eZProtectedContentBundle\Listener\PasswordProvided:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: 'onKernelRequest', priority: -100}
