#ddev-generated
services:
  solr:
    image: solr:9-${DDEV_SITENAME}-built
    build:
      dockerfile_inline: |
        ARG SOLR_BASE_IMAGE="scratch"
        FROM $$SOLR_BASE_IMAGE
        # Fix HTTPS redirect to HTTP which breaks URL for Solr Admin UI.
        # The reason for this problem is that Solr uses Jetty as a webserver.
        # Jetty has X-Forwarded- headers disabled by default, enable them here:
        USER root
        RUN sed -i '/X-Forwarded-/,/-->/ {/<!--/d; /-->/d}' /opt/solr/server/etc/jetty.xml
        # Use predefined values for username/password in Solr Admin UI.
        RUN sed -i "/\$$rootScope.exceptions = {};/a \$$scope.username = 'solr'; \$$scope.password = 'SolrRocks';" /opt/solr/server/solr-webapp/webapp/js/angular/controllers/login.js
        USER solr
      args:
        SOLR_BASE_IMAGE: solr:9
    container_name: ddev-${DDEV_SITENAME}-solr
    expose:
      - 8983
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    environment:
      SOLR_HOST: ddev-${DDEV_SITENAME}-solr
      SOLR_PORT: 8983
      # The pre-trained OpenNLP models require a much bigger buffer.
      SOLR_OPTS: -Djute.maxbuffer=50000000
      #SOLR_HEAP: 1g
      SOLR_AUTH_TYPE: basic
      SOLR_AUTHENTICATION_OPTS: -Dbasicauth=solr:SolrRocks
      # needed for Drupal Search API Solr
      SOLR_MODULES: ${SOLR_MODULES-extraction,langid,ltr,analysis-extras}
      VIRTUAL_HOST: ${DDEV_HOSTNAME}
      HTTP_EXPOSE: 8983:8983
      HTTPS_EXPOSE: 8943:8983
    volumes:
      - .:/mnt/ddev_config
      - ddev-global-cache:/mnt/ddev-global-cache
      - ./solr/lib:/opt/solr/modules/ddev/lib
      - solr:/var/solr
    command:
      - bash
      - -c
      - |
        set -eu -o pipefail
        docker-entrypoint.sh solr start -c -Dlog4j.configurationFile=/opt/solr/server/resources/log4j2-console.xml
        solr zk cp file:/mnt/ddev_config/solr/security.json zk:/security.json -z localhost:9983
        cd /mnt/ddev_config/solr/configsets
        for dir in */; do
          dir="$${dir%/}"
          if [[ "$$dir" != "*" ]]; then
            echo "uploading configset $$dir"
            solr zk upconfig -n "$$dir" -d "$$dir" -z localhost:9983
            echo "creating collection $$dir"
            solr create -c "$$dir" -n "$$dir" -shards 1 -replicationFactor 1 || true
          fi
        done
        cd -
        solr stop > /dev/null
        exec solr-foreground -c -Dlog4j.configurationFile=/opt/solr/server/resources/log4j2.xml
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s localhost:8983/solr/"]

volumes:
  solr:
