parameters:
    env(ENABLE_IMAGE_PLACEHOLDER): true
    env(VIEW_MATCHER_FIELD_IDENTIFIER): 'matcher'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Novactive\Bundle\eZExtraBundle\Command\CreateContentTypesCommand:
        bind:
            $translationHelper: "@Ibexa\\Core\\Helper\\TranslationHelper"

    Novactive\Bundle\eZExtraBundle\Core\Helper\eZ\WrapperFactory: ~
    Novactive\Bundle\eZExtraBundle\Core\Manager\eZ\Content: ~
    Novactive\Bundle\eZExtraBundle\Core\Manager\eZ\ContentType: ~
    Novactive\Bundle\eZExtraBundle\Core\Helper\eZ\Content: ~

    Novactive\Bundle\eZExtraBundle\Twig\ContentExtension: ~
    Novactive\Bundle\eZExtraBundle\Twig\TextParsingExtension: ~
    Novactive\Bundle\eZExtraBundle\Twig\ImageExtension:
        bind:
            $enableImagePlaceholder: '%env(bool:ENABLE_IMAGE_PLACEHOLDER)%'

    Novactive\Bundle\eZExtraBundle\EventListener\PreContentViewListener:
        arguments:
            $templateGlobalHelper: '@ibexa.templating.global_helper'

    Novactive\Bundle\eZExtraBundle\Core\ViewMatcher\ContentTypeField:
        tags: [ 'ibexa.view.matcher' ]
        bind:
            $fieldIdentifier: '%env(VIEW_MATCHER_FIELD_IDENTIFIER)%'
